### ISSUE TITLE
Task Update

### ISSUE THREAD

**Issue by Olivia-liu99** [yolominds/seacows-test#1]
**Background Info**
What is Seacows?
SeaCows is a decentralized NFT AMM powered by AI-driven price oracles to enable instant NFT trading. Website:https://seacows.io/

What is NFT AMM？
An NFT AMM is a decentralized alternative to centralized marketplaces such as Opensea or Magic Eden. Unlike a bid-and-buy model, it utilizes liquidity pools to allow for frictionless, low-cost trading.
Documentation: https://docs.seacows.io/nft-amm-deep-dives/user-guide

**What to do?**
There are a few fundamental functions of Seacows, including swapping (buy and sell in a centralized marketplace), creating the pool, and withdrawing liquidity. What needed to do in this test is swapping. 

**Tasks:**
1. Link to metamask wallet, get balance of erc20, and display
2. Read nft from the pool, show its metadata, and its quote from the pool.
3. Mint testnet nft to your own wallet(however, don't upload your private key), and implement a list to simply display nft
4. approve nft to contract
5. call contract to swap testnet nft for testnet token (nft to token swap)

**Comment by Franceshe** [comment]
Merged to front-end-eng
